# Generated by Django 3.1 on 2025-05-02 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('users', '0002_auto_20250502_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='student',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='user',
            name='stud_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.classes', verbose_name='Класс'),
        ),
    ]
