# Generated by Django 3.1 on 2025-05-02 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20250502_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='student',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='marks', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Ученик'),
        ),
    ]
