# Generated by Django 3.1 on 2025-04-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(blank=True, choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2')], max_length=1, null=True)),
                ('algebra', models.CharField(blank=True, choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2')], max_length=1, null=True)),
                ('chemistry', models.CharField(blank=True, choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2')], max_length=1, null=True)),
                ('drawing', models.CharField(blank=True, choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2')], max_length=1, null=True)),
                ('physics', models.CharField(blank=True, choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2')], max_length=1, null=True)),
                ('math', models.CharField(blank=True, choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2')], max_length=1, null=True)),
            ],
        ),
    ]
