# Generated by Django 3.1 on 2025-04-23 15:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='student',
            field=models.ManyToManyField(related_name='Учащийся', to=settings.AUTH_USER_MODEL, verbose_name='Класс'),
        ),
    ]
