# Generated by Django 3.1 on 2025-05-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='role',
            field=models.TextField(blank=True, null=True),
        ),
    ]
